config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  
  resources  :events
  devise_for :users
  resources  :users, only: :show 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  after_create :attendance_created

  def attendance_created
    UserMailer.attendance_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date,
    presence: {message: 'Date de départ obligatoire'}
    validate :start_date_is_past

  validates :duration, 
    presence: {message: 'Durée obligatoire'},
    numericality: {greater_than: 0}
    validate :is_duration_multiple_5

  validates :title,
    presence: {message: "Titre obligatoire"},
    length: {in: 5..140}

  validates :description,
    presence: {message: "Description obligatoire"},
    length: {in: 20..1000}

  validates :price,
    presence: {message: "Prix obligatoire"},
    numericality: {only_integer: true, greater_than: 0, less_than: 1000, message: "Le prix doit être compris entre 1 et 1 000"}

  validates :location,
    presence: {message: "Lieu obligatoire"}
  
  has_many :attendances, dependent: :destroy
  has_many :users, through: :attendances
  belongs_to :admin, class_name: 'User'

  def start_date_is_past
    if start_date.past?
      errors.add(:start_date, "Date non valide")
    end
  end

  def is_duration_multiple_5
    if duration % 5 != 0
      errors.add(:duration, "La durée doit être un multiple de 5")
    end
  end

  def end_date 
    @end_date = start_date + duration*60
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :attendances, dependent: :destroy
  has_many :events, through: :attendances
  has_many :events, foreign_key: 'admin_id', class_name: 'Event', dependent: :destroy

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except:[:index]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    p "$"*60
    p params
    @event = Event.new(title:params[:title],description:params[:description],admin_id:current_user.id,duration:params[:duration],location:params[:location],price:params[:price],start_date:params[:start_date].to_datetime)
    p @event
    if @event.save
      redirect_to root_path, notice: "L'évènement '#{@event.title.capitalize}' a bien été créé ! Félicitation"
    else
      flash.now[:messages] = @event.errors.full_messages
      render new_event_path
    end
  end

  def edit 
  end

  def update 
  end

  def show
    @event = Event.find(params[:id])
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(current_user.id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<div class="jumbotron py-4 bg-light border-5 border-bottom border-warning">
    <div class="container">
      <h1 class="display-3">C'est la rouille?<span class='yellow'>...</span> </h1>
        <p>Ici tu trouveras de quoi t'occuper! Seul ou avec tes potes!</p>
        <p>Tu peux également réunir du monde en créant toi meme ton évenement!</p>
        <p><a class="btn btn-outline-warning btn-lg" href='<%=new_event_path%>' role="button">On y va!</a></p>
  </div>
</div>

<div class="container py-3  ">
  
  <div class="row">
    <%@events.each do |event|%>
      <div class="col-md-4 p-5">
        <h2><%=event.title%></h2>
        <p><%=event.description%></p> 
        <p><%=event.start_date.to_date%>
        <p><a class="btn btn-outline-warning" href=<%=event_path(event.id)%> role="button">Détails »</a></p>
      </div>
    <%end%>
  </div>  
  <hr>
</div>

app/views/events/new.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%=form_tag url_for(action: 'create'),class: "form-signin mt-3", method: "post" do %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Créer un évènement</h1>

        <div class='form-group'>
          <label>Titre</label><br>
          <%= text_field_tag 'title',"", class: 'form-control'%>
        </div>

        <div class='form-group'>
          <label>Description</label><br>
          <%= text_area_tag 'description',"", class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Durée</label><br>
          <%= number_field_tag 'duration',"", class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Prix</label><br>
          <%= number_field_tag 'price',"", class:'form-control'%>
        </div>

        <div class='form-group'>
          <label>Lieu</label><br>
          <%= text_field_tag 'location',"", class:'form-control'%>
        </div>  

        <div class='form-group'>
          <label>Date et heure de départ</label><br>
          <%= datetime_local_field_tag 'start_date',"", class:'form-control'%>
        </div>  

        <br>

        <div class='form-group'>

          <button type=submit class='btn btn-outline-warning'>Créer l'évènement</button>

        </div>
      <% end %>
      <%= link_to "Retour", root_path %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class='container'>
  <div class='containerfluid my-5'>
    <h2><%=@event.title%> <span class='text-muted'>by <%=@event.admin.email%></span></h2>
    <hr>
    <p>Lieu : <%=@event.location%></p>
    <p>Date de début : <%=@event.start_date%></p>
    <p>Date de fin : <%=@event.end_date%>
    <hr>
    <p>Nombre de personnne(s): <%=@event.attendances.size%>
    <p>Prix : <%=@event.price%> €
    <hr class='border-3 border border-warning'>
    <p>Description:</p>
    <p class='mx-5'>>>> <%=@event.description%></p>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EvenTHP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--Favicon -->
    <%= favicon_link_tag 'https://image.flaticon.com/icons/png/512/38/38706.png'%>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!--CSS  Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  </head>

  <body>
    <!--HEADER navbar -->
    <header class= 'fixed-top'>
      <div class="px-3 py-2 bg-dark text-white">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-between">
            
            <div>
              <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-emoji-dizzy-fill" viewBox="0 0 16 16">
                  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zM4.146 5.146a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 1 1 .708.708l-.647.646.647.646a.5.5 0 1 1-.708.708L5.5 7.207l-.646.647a.5.5 0 1 1-.708-.708l.647-.646-.647-.646a.5.5 0 0 1 0-.708zm5 0a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708.708l-.647.646.647.646a.5.5 0 0 1-.708.708l-.646-.647-.646.647a.5.5 0 1 1-.708-.708l.647-.646-.647-.646a.5.5 0 0 1 0-.708zM8 13a2 2 0 1 1 0-4 2 2 0 0 1 0 4z"/>
                </svg> <span class= 'name mx-2'>Even<span class='green'>THP</span></span>
              </a>
            </div>

            <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
              <li class='nav-item'>
                <a href="/" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-speedometer2" viewBox="0 0 16 16">
                  <path d="M8 4a.5.5 0 0 1 .5.5V6a.5.5 0 0 1-1 0V4.5A.5.5 0 0 1 8 4zM3.732 5.732a.5.5 0 0 1 .707 0l.915.914a.5.5 0 1 1-.708.708l-.914-.915a.5.5 0 0 1 0-.707zM2 10a.5.5 0 0 1 .5-.5h1.586a.5.5 0 0 1 0 1H2.5A.5.5 0 0 1 2 10zm9.5 0a.5.5 0 0 1 .5-.5h1.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5zm.754-4.246a.389.389 0 0 0-.527-.02L7.547 9.31a.91.91 0 1 0 1.302 1.258l3.434-4.297a.389.389 0 0 0-.029-.518z"/>
                  <path fill-rule="evenodd" d="M0 10a8 8 0 1 1 15.547 2.661c-.442 1.253-1.845 1.602-2.932 1.25C11.309 13.488 9.475 13 8 13c-1.474 0-3.31.488-4.615.911-1.087.352-2.49.003-2.932-1.25A7.988 7.988 0 0 1 0 10zm8-7a7 7 0 0 0-6.603 9.329c.203.575.923.876 1.68.63C4.397 12.533 6.358 12 8 12s3.604.532 4.923.96c.757.245 1.477-.056 1.68-.631A7 7 0 0 0 8 3z"/>
                </svg>
                  Accueil
                </a>
              </li>
              <li>
                <a href='<%=new_event_path%>' class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-calendar-event" viewBox="0 0 16 16">
                  <path d="M11 6.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z"/>
                  <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
                </svg>
                  Céer un évent
                </a>
              </li>
            </ul>

            <div class="dropdown">
              <% if user_signed_in?  %>
                <button class="btn btn-outline-warning dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">Mon profil</button>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                  <li><a class="dropdown-item" href="<%=user_path(current_user.id)%>">Mon profil</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="<%=destroy_user_session_path%>" data-method='delete'>Se déconnecter</a></li>
              </ul>
              <% else %>
                <button class="btn btn-outline-warning dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">S'inscrire/Se connecter</button>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                  <li><a class="dropdown-item" href='<%=new_user_registration_path%>'>S'inscrire</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href='<%=new_user_session_path%>'>Se connecter</a></li>
                  </ul>
                <%end%>
            </div>
            
          </div>
        </div>
      </div>
    </header>

    <!--Alertes -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>





    <%= yield %>


    <!--Footer -->
    <footer class="footer mt-auto py-1 bg-light fixed-bottom">
      <div class="container">
        <span class="text-muted">© Created by The Power Coders & THP</span>
      </div>
    </footer>

    <!--JS Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

  </body>
</html>

app/views/users/show.html.erb
<div class='container'>
  <div class='containerfluid mt-5'>
    <h2>Profil utilisateur</h2>
    <hr class='border border-3 border border-warning'>
    <p>Prénom :<%=@user.first_name%></p>
    <p>Nom :<%=@user.last_name%></p>
    <p>Description : <%=@user.description%>
    <p>Email : <%=@user.email%></p>
  </div>
  <hr>
  <div class='containerfluid'>
    <a class="btn btn-outline-warning" href="<%=edit_user_registration_path%>">Modifier</a>
  </div> 
  <hr>
  <h2>Les évènements crées :</h2>
  <div class="row">
    <%@user.events.each do |event|%>
      <div class="col-md-4 p-5">
        <h2><%=event.title%></h2>
        <p><%=event.description%></p>
        <p><%=event.start_date.to_date%>
        <p><a class="btn btn-outline-warning" href="href=<%=event_path(event.id)%>" role="button">Détails »</a></p>
      </div>
    <%end%>
  </div>  
</div>